```
<시퀀스 도구 생성>
CREATE TABLE DEPT_SEQUENCE
AS SELECT * FROM DEPT WHERE 1<>1;
SELECT * FROM DEPT_SEQUENCE;
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 0
NOCYCLE
CACHE 2;

INSERT INTO DEPT_SEQUENCE (DEPTNO,DNAME,LOC) VALUES 
(SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','ANDONG');
SELECT * FROM DEPT_SEQUENCE;
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;
```
```
