```--Q1
SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL 
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.SAL > 2000
ORDER BY DEPTNO;

SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
WHERE E.SAL > 2000;
```
```
--Q2
SELECT D.DEPTNO,D.DNAME,TRUNC(AVG(E.SAL),0)AS AVG_SAL,MAX(E.SAL)AS MAX_SAL,MIN(E.SAL)AS MIN_SAL,
COUNT(*)AS CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO,D.DNAME;
```
```
--Q3
SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.JOB,E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO ORDER BY DEPTNO,ENAME;

SELECT DEPTNO,DNAME,EMPNO,ENAME,JOB,SAL
FROM EMP NATURAL JOIN DEPT ORDER BY DEPTNO,ENAME;


SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.JOB,E.SAL
FROM DEPT D JOIN EMP E ON(D.DEPTNO = E.DEPTNO)
ORDER BY DEPTNO, ENAME;
```
```
--Q4
SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.MGR,E.SAL,E.DEPTNO,
S.LOSAL,S.HISAL,S.GRADE,E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_ENAME
FROM DEPT D,EMP E,SALGRADE S,EMP E2
WHERE D.DEPTNO(+) = E.DEPTNO
AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
   AND E.MGR = E2.EMPNO(+)
ORDER BY D.DEPTNO,E.DEPTNO;
```
```
<P.324 연습문제>
--Q1
CREATE TABLE EMP_HW
AS SELECT * FROM EMP;
TRUNCATE TABLE EMP_HW;
SELECT * FROM EMP_HW;
DESC EMP_HW;
--Q2
ALTER TABLE EMP_HW ADD BIGO VARCHAR2(20);
--Q3
ALTER TABLE EMP_HW MODIFY BIGO VARCHAR2(30);
--Q4
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;
```
