```
<제약조건>
CREATE TABLE DEPT_CONST(
DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE ,
LOC VARCHAR2(13) CONSTRAINT DEPTCONT_LOC_NN NOT NULL);
SELECT * FROM DEPT_CONST;
DESC DEPT_CONST;
```
```
<권한부여>
SELECT * FROM HELP;
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;
GRANT CREATE SESSION TO ORCLSTUDY;
SELECT * FROM ALL_USERS;
WHERE USERNAME = 'ORCLSTUDY';
SELECT * FROM DBA_OBJECTS;

DROP USER ORCLSTUDY;
COMMIT;

CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;
REVOKE RESOURCE FROM ORCLSTUDY;
SELECT * FROM ALL_USERS;
```
```
<PL/SQL>
SET SERVEROUTPUT ON;
BEGIN
DBMS_OUTPUT.PUT_LINE('HELL0, PL/SQL!');
END;
/
-----한 줄 주석 사용하기
DECLARE
V_EMPNO NUMBER(4) := 7788;
V_ENAME VARCHAR2(10);
BEGIN
V_ENAME := 'SCOTT';
DBMS_OUTPUT.PUT_LINE('V_EMPNO : ' || V_EMPNO);
DBMS_OUTPUT.PUT_LINE('V_ENAME : ' || V_ENAME);
END;
/
--연습
DECLARE
V_DEPTNO NUMBER(4);
V_DNAME VARCHAR2(10);
V_LOC VARCHAR2(10);
BEGIN
V_DEPTNO := 10;
V_DNAME := '홍길동';
V_LOC := '안동';
DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
DBMS_OUTPUT.PUT_LINE('V_DNAME : ' || V_DNAME);
DBMS_OUTPUT.PUT_LINE('V_LOC : ' || V_LOC);
END;
/
  ```
  ```
  <IF문 / CASE문>
DECLARE
V_NUMBER NUMBER DEFAULT 12;
BEGIN
IF MOD(V_NUMBER,2) = 1 THEN
    DBMS_OUTPUT.PUT_LINE('홀수 입니다');
ELSE 
    DBMS_OUTPUT.PUT_LINE('짝수 입니다');
END IF;
END;
/
COMMIT;
DECLARE
V_SCORE NUMBER DEFAULT 87;
BEGIN
CASE TRUNC(V_SCORE/10)
WHEN 10 THEN DBMS_OUTPUT.PUT_LINE('A학점');
WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('B학점');
ELSE  DBMS_OUTPUT.PUT_LINE('F학점');
END CASE;
END;
/
  ```
  ```
<loop문>
DECLARE
V_NUM NUMBER := 0;
BEGIN
    LOOP
DBMS_OUTPUT.PUT_LINE(V_NUM);
V_NUM := V_NUM + 1;
EXIT WHEN V_NUM > 4;
END LOOP;
END;
/
<WHILE문>
  DECLARE
V_NUM NUMBER := 0;
BEGIN
WHILE V_NUM < 4 LOOP
DBMS_OUTPUT.PUT_LINE(V_NUM);
V_NUM := V_NUM + 1;
END LOOP;
END;
/
  ```
  ```
