```
<짝수 3,6,9 출력>
FOR I IN 1..10 LOOP
IF MOD(I,3) = 0 THEN
DBMS_OUTPUT.PUT_LINE('출력 : ' || I);
END IF;
END LOOP;
END;
/
  
<0~4 뒤집어서 출력>
DECLARE
BEGIN
FOR I IN REVERSE 0..4 LOOP
DBMS_OUTPUT.PUT_LINE('현재 I의 값 : ' || I);
END LOOP;
END;
/
```
```
--레코드 정의 사용
DECLARE
TYPE REC_DEPT IS RECORD(
deptno NUMBER(2) NOT NULL := 99,
dname DEPT.DNAME%TYPE,
loc DEPT.LOC%TYPE);
dept_rec REC_DEPT;
BEGIN
dept_rec.deptno := 99;
dept_rec.dname := 'DATABASE';
dept_rec.loc := 'SEOUL';
DBMS_OUTPUT.PUT_LINE(dept_rec.deptno);
DBMS_OUTPUT.PUT_LINE(dept_rec.dname);
DBMS_OUTPUT.PUT_LINE(dept_rec.loc);
END;
/
  ```
  ```
  DECLARE
 V_DEPT_ROW DEPT%ROWTYPE;
 BEGIN
 SELECT DEPTNO,DNAME,LOC INTO V_DEPT_ROW FROM DEPT
 WHERE DEPTNO = 40;
DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.DEPTNO);
DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.DNAME);
DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.LOC);
 END;
 /
 
 --18-2 단일행 데이터 저장하는 커서 사용
 DECLARE
 V_DEPT_ROW DEPT%ROWTYPE;
 --명시적 커서 선언
 CURSOR C1 IS SELECT DEPTNO,DNAME,LOC FROM DEPT WHERE DEPTNO = 40;
 BEGIN
 --커서 열기
 OPEN C1;
 --데이터 가공
 FETCH C1 INTO V_DEPT_ROW;
 DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.DEPTNO);
DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.DNAME);
DBMS_OUTPUT.PUT_LINE(V_DEPT_ROW.LOC);
--커서닫기 리소스 반환
CLOSE C1;
 END;
 /
   ```
