```
<SQL 퀴즈 문제>
1. SELECT * FROM EMP WHERE ENAME LIKE '%S';
2. SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
3. SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO IN (20,30) AND SAL > 2000;

SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO = 20 AND SAL > 2000
UNION
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO = 30  AND SAL > 2000;
4. SELECT * FROM EMP WHERE NOT SAL >= 2000 AND SAL <=3000;
5. SELECT ENAME,EMPNO,SAL,DEPTNO FROM EMP WHERE ENAME LIKE '%E%' AND

DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;
6. SELECT * FROM EMP WHERE COMM IS NULL AND JOB IN('CLERK','MANAGER') AND

ENAME NOT LIKE '_L%';
```
```
<SQL 퀴즈문제 2>
  --Q1
SELECT EMPNO,RPAD(SUBSTR(EMPNO,-LENGTH(EMPNO),2),4,'*')AS MASKING_EMPNO,
ENAME,RPAD(SUBSTR(ENAME,-LENGTH(ENAME),1),5,'*')AS MASKING_ENAME
FROM EMP WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;
--Q2
SELECT EMPNO,ENAME,SAL,TRUNC((SAL/21.5),2)AS DAY_PAY,
ROUND(((SAL/21.5)/8),1)AS TIME_PAY
FROM EMP;
--Q3
SELECT EMPNO,ENAME,TO_CHAR(HIREDATE,'YYYY/MM/DD')AS HIREDATE,
TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월요일'),'YYYY-MM-DD')AS R_JOB,
NVL(TO_CHAR(COMM),'N/A')AS COMM
FROM EMP;
--Q4
SELECT EMPNO,ENAME,MGR,
CASE WHEN MGR IS NULL THEN 0000
WHEN SUBSTR(MGR,-LENGTH(MGR),2)='75' THEN 5555
WHEN SUBSTR(MGR,-LENGTH(MGR),2)='76' THEN 6666
WHEN SUBSTR(MGR,-LENGTH(MGR),2)='77' THEN 7777
WHEN SUBSTR(MGR,-LENGTH(MGR),2)='78' THEN 8888
ELSE MGR END AS CHG_MGR FROM EMP;
```
```
